repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-build
      - id: golangci-lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        types_or:
          - javascript
          - markdown
          - html
          - css
          - yaml
          - json
